name: Publish Retype powered website to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish to GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - uses: retypeapp/action-build@latest
        with:
          license: ${{ secrets.RETYPE_LICENSE }}

      - uses: retypeapp/action-github-pages@latest
        with:
          branch: gh-pages
          update-branch: true 